# Generated by Django 4.2 on 2023-05-19 18:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(default='Player_first_name', max_length=255)),
                ('last_name', models.TextField(default='Player_last_name', max_length=255)),
                ('user_pick', models.ImageField(blank=True, default='media/default/200px-Wojak.png', null=True, upload_to='media/custom')),
                ('country', models.TextField(null=True)),
                ('age', models.IntegerField(null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('about', models.TextField(max_length=255, null=True)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
