# Generated by Django 4.2 on 2023-05-12 14:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('What_is_mem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 12, 17, 6, 35, 120076)),
        ),
    ]
